from pydantic import BaseModel, Field
from typing import Optional

# =====================================================================
# schemas.py
# This file defines the Pydantic models used for requests and responses.
# Pydantic automatically validates incoming data types and formats the output data.
# =====================================================================

class EmployeeBase(BaseModel):
    """
    Base model containing fields that are common to both creating and reading employees.
    This helps avoid code duplication.
    """
    name: str = Field(..., min_length=2, max_length=50, description="Full name of the employee")
    email: str = Field(..., description="Email address of the employee (e.g., alex@company.com)")
    department: str = Field(..., min_length=2, max_length=50, description="Department name (e.g., Engineering, HR)")
    role: str = Field(..., min_length=2, max_length=50, description="Job title / role (e.g., Frontend Developer)")


class EmployeeCreate(EmployeeBase):
    """
    Model for creating a new employee.
    Inherits all fields from EmployeeBase. No additional fields are needed at creation.
    """
    pass


class EmployeeUpdate(BaseModel):
    """
    Model for updating an existing employee.
    All fields are optional to allow partial updates during a PUT request.
    If a field is not provided, it will not be updated.
    """
    name: Optional[str] = Field(None, min_length=2, max_length=50)
    email: Optional[str] = None
    department: Optional[str] = Field(None, min_length=2, max_length=50)
    role: Optional[str] = Field(None, min_length=2, max_length=50)


class Employee(EmployeeBase):
    """
    Model representing an Employee stored in our system.
    This extends EmployeeBase by adding the 'id' field, which is generated by the server.
    """
    id: int

    class Config:
        # Configures Pydantic to support reading data from object attributes (e.g. database models)
        from_attributes = True
